adaptation/urls.py
from django.urls import path,re_path
from . import views

app_name = 'adaptation'
urlpatterns = [
    path('', views.base, name='base'), #for startTracking
    path('bg_extension1/',views.bg_extension1, name='bg_extension1'),
    path('bg_extension2/',views.bg_extension2, name='bg_extension2'),
    path('bg_extension3/',views.bg_extension3, name='bg_extension3'),
    path('bg_extension4/',views.bg_extension4, name='bg_extension4'),

    path('font_type_extension1/',views.font_type_extension1, name='font_type_extension1'),
    path('font_type_extension2/',views.font_type_extension2, name='font_type_extension2'),
    path('font_type_extension3/',views.font_type_extension3, name='font_type_extension3'),
    path('font_type_extension4/',views.font_type_extension4, name='font_type_extension4'),
    path('font_type_extension5/',views.font_type_extension5, name='font_type_extension5'),
    path('font_type_extension6/',views.font_type_extension6, name='font_type_extension6'),
    path('font_type_extension7/',views.font_type_extension7, name='font_type_extension7'),

    path('text_color_extension/',views.text_color_extension, name='text_color_extension'),

    path('char_spacing_extension1/',views.char_spacing_extension1, name='char_spacing_extension1'),
    path('char_spacing_extension2/',views.char_spacing_extension2, name='char_spacing_extension2'),

    path('stopTracking/',views.stopTracking, name='stopTracking'),

    path('adaptation_result/',views.adaptation_result, name='adaptation_result'),

    re_path(r'.*save_gaze_data/$', views.save_gaze_data, name='save_gaze_data'),

]

authentication/urls.py
from django.urls import path
from . import views

app_name ='authentication'

urlpatterns=[
    path('home/', views.home, name='home'),
    path('signin/', views.signin, name='signin'),
    path('register/', views.register, name='register'),
    path('register-player/', views.register_player, name='register-player'),
    path('register-parent-teacher/', views.register_parent_teacher, name='register-parent-teacher'),
    path('user_login/', views.user_login, name='user_login'),
]

dyslexia_project/urls.py
from django.contrib import admin
from django.urls import path,include
from authentication import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('test/', include('gamified_test.urls' , namespace='gamified_test')),
    path('authentication/', include('authentication.urls' , namespace= 'authentication')),
    path('eyeTracking/', include('eyeTracking.urls' , namespace= 'eyeTracking')),
    path('adaptation/', include('adaptation.urls' , namespace= 'adaptation')),
    path('logout/', views.user_logout, name='logout'),
]

gamified_test/urls.py
from django.urls import path
from . import views

app_name = 'gamified_test'

urlpatterns = [
    path('signin/', views.signin, name='signin'),
    path('register/', views.register, name='register'),
    path('q1Screen/', views.q1Screen, name='q1Screen'),
    path('q2Screen/', views.q2Screen, name='q2Screen'),
    path('q3Screen/', views.q3Screen, name='q3Screen'),
    path('q4Screen/', views.q4Screen, name='q4Screen'),
    path('q5Screen/', views.q5Screen, name='q5Screen'),
    path('q6Screen/', views.q6Screen, name='q6Screen'),
    path('q7Screen/', views.q7Screen, name='q7Screen'),
    path('q8Screen/', views.q8Screen, name='q8Screen'),
    path('q9Screen/', views.q9Screen, name='q9Screen'),
    path('q10Screen/', views.q10Screen, name='q10Screen'),
    path('q11Screen/', views.q11Screen, name='q11Screen'),
    path('q12Screen/', views.q12Screen, name='q12Screen'),
    path('q13Screen/', views.q13Screen, name='q13Screen'),
    path('q14Screen/', views.q14Screen, name='q14Screen'),
    path('q15Screen/', views.q15Screen, name='q15Screen'),
    path('q16Screen/', views.q16Screen, name='q16Screen'),
    path('q17Screen/', views.q17Screen, name='q17Screen'),
    path('q18Screen/', views.q18Screen, name='q18Screen'),
    path('q19Screen/', views.q19Screen, name='q19Screen'),
    path('q20Screen/', views.q20Screen, name='q20Screen'),
    path('q21Screen/', views.q21Screen, name='q21Screen'),
    path('q22Screen/', views.q22Screen, name='q22Screen'),
    path('q23Screen/', views.q23Screen, name='q23Screen'),
    path('q24Screen/', views.q24Screen, name='q24Screen'),
    path('q25Screen/', views.q25Screen, name='q25Screen'),
    path('q26Screen/', views.q26Screen, name='q26Screen'),
    path('q27Screen/', views.q27Screen, name='q27Screen'),
    path('q28Screen/', views.q28Screen, name='q28Screen'),
    path('q29Screen/', views.q29Screen, name='q29Screen'),
    path('q30Screen/', views.q30Screen, name='q30Screen'),
    path('q31Screen/', views.q31Screen, name='q31Screen'),
    path('q32Screen/', views.q32Screen, name='q32Screen'),
    path('save_performance_data/<int:exercise_num>/', views.save_performance_data, name='save_performance_data'),
    path('result/', views.result, name='result'),
    path('statistical_result/',views.result,name='statistical_result'),
]

authentication/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Player(models.Model):
    user = models.OneToOneField(User , on_delete=models.CASCADE )
    # additional fields
    nationalId = models.CharField(max_length = 256)
    age = models.IntegerField()
    gender = models.CharField(max_length = 50)
    isNative = models.BooleanField(max_length = 50)
    failedLang = models.BooleanField(max_length = 50)

    def __str__(self):
        return self.user.username
class Parent_Teacher(models.Model):
    user = models.OneToOneField(User , on_delete=models.CASCADE )
    # additional fields
    nationalId = models.CharField(max_length = 256)

    def __str__(self):
        return self.user.username

authentication/forms.py
from django.contrib.auth.models import User
from authentication.models import Player,Parent_Teacher
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

    def __init__(self, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        # Update attributes for username field separately
        self.fields['username'].widget.attrs.update({
            'class': 'form-control',
            'id': 'usernameInputId',
            'aria-describedby': 'usernameHelp',
        })
        # Update attributes for other fields
        for field in ['email', 'password']:
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
            })

class PlayerForm(forms.ModelForm):
     YES_NO_CHOICES = [
        (True, 'Yes'),
        (False, 'No'),
    ]
     GENDER_CHOICES = [
        ("male", 'Male'),
        ("female", 'Female'),
    ]
     nationalId = forms.CharField(widget=forms.TextInput(attrs={'id': 'nationaId'}))
     age = forms.IntegerField(widget=forms.NumberInput(attrs={'id': 'age'}))
     gender = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.Select(attrs={'id': 'gender'}))
     isNative = forms.ChoiceField(choices=YES_NO_CHOICES,widget=forms.Select(attrs={'id': 'isNative'}))
     failedLang = forms.ChoiceField(choices=YES_NO_CHOICES,widget=forms.Select(attrs={'id': 'failedLang'}))

     def __init__(self, *args, **kwargs):
        super(PlayerForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
        })

     class Meta():
        model = Player
        fields =('isNative' , 'failedLang' ,'nationalId' ,'gender' ,'age')
    
class Parent_TeacherForm(forms.ModelForm):
     nationalId = forms.CharField(widget=forms.TextInput(attrs={'id': 'nationaId'}))

     def __init__(self, *args, **kwargs):
        super(Parent_TeacherForm, self).__init__(*args, **kwargs)
        for field in iter(self.fields):
            self.fields[field].widget.attrs.update({
                'class': 'form-control'
        })

     class Meta():
        model = Parent_Teacher
        fields =('nationalId',)
    

authentication/views.py
from django.shortcuts import render
from authentication.forms import PlayerForm,UserForm,Parent_TeacherForm
from django.contrib.auth import login,logout,authenticate
from django.http import HttpResponseRedirect,HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def home(request):
    registered = request.GET.get('registered', False)  
    return render(request , 'authentication/home.html' ,{'registered': registered})

def signin(request):
    return render(request , 'authentication/signin.html')

def register(request):
    userForm = UserForm()
    playerForm = PlayerForm()
    parent_teacherForm = Parent_TeacherForm()

    return render(request , 'authentication/register.html' , {
        'userForm': userForm,
        'playerForm': playerForm,
        'parent_teacherForm': parent_teacherForm
    })

def register_player(request):
    if request.method == 'POST':  
        userForm = UserForm(data=request.POST)
        playerForm = PlayerForm(data=request.POST)
        
        if userForm.is_valid() and playerForm.is_valid():
            user = userForm.save()
            user.set_password(user.password)
            user.save()

            player = playerForm.save(commit=False)  # Get unsaved instance
            player.user = user  # Assign user to player
            player.save()  # Save player instance
            return HttpResponseRedirect(reverse('home'))
        else:
            print(userForm.errors, playerForm.errors)  
    else:
        userForm = UserForm()
        playerForm = PlayerForm()
        
    return render(request, 'authentication/register.html', {
        'userForm': userForm,
        'playerForm': playerForm,
    })
def register_parent_teacher(request):
    if request.method == 'POST':  
        userForm = UserForm(data=request.POST)
        parent_teacherForm = Parent_TeacherForm(data=request.POST)
        
        if userForm.is_valid() and parent_teacherForm.is_valid():
            user = userForm.save()
            user.set_password(user.password)
            user.save()

            p = parent_teacherForm.save(commit=False)  # Get unsaved instance
            p.user = user  # Assign user to player
            p.save()  # Save player instance
            return HttpResponseRedirect(reverse('home'))
        else:
            print(userForm.errors, parent_teacherForm.errors)  
    else:
        userForm = UserForm()
        parent_teacherForm = Parent_TeacherForm()
        
    return render(request, 'authentication/register.html', {
        'userForm': userForm,
        'parent_teacherForm': parent_teacherForm,
    })

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username = username , password = password)
        
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('home'))
            else:
                return HttpResponse("inactive account")
        else:
            return HttpResponse("invalid data")
    else:
        return render(request, 'authentication/signin.html',{})
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('home'))

authentication/templates/authentication/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Include jquery -->
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
     <!-- Bootstrap Documentation Links -->
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
  </head>
  <style>
    .navbar {
        position: fixed;
        top: 0;
        width: 100%;
        z-index: 1030;  /* Set a higher z-index to ensure navbar stays on top while scrolling. */
    }
    .container {
       margin-top: 100px; 
    }
  </style>
  <body>
    {%include 'authentication/navbar.html'%}
    {%block content%}
    {%endblock%}
  </body>
</html>
     

authentication/templates/authentication/home.html
{%extends "authentication/base.html"%}

{%block content%}
{%load static%}
<link rel="stylesheet" href="{%static 'authentication/css/home.css'%}">
<style>
    .jumbotron {
        margin-top: 50px;
        background: url('{% static "authentication/Child-Reading.png" %}') center center/cover no-repeat;
        position: relative;
        color: #fff;
        text-align: left;
        overflow: hidden;
        width: 100%;
    }
</style>
    <div class="jumbotron">
        <div class="jumbotron-content">
            <h1 class="display-4">What is Dyadapt?</h1>
            <p class="lead">
            With Dyadapt, you will improve your reading experience. 
            You will also have access to the Dyadapt screening test that allows you, in just 15 minutes,to detect if your child is dyslexic or not, 
            through playing a game personalized based on 24 cognitive skills targeting both cognitive weaknesses and strengths.   
            Additionally, Dyadapt uses advanced eye-tracking technology to help identify dyslexia by analyzing reading patterns and eye movements, providing a comprehensive and accurate screening process. 
            We also offer a browser extension that enhances readability for dyslexics by adjusting webpage content for a better browsing experience.
            </p>
            {% if user.is_authenticated%}
            <a class="btn btn-primary btn-lg" href="{% url 'gamified_test:q1Screen' %}" role="button">Start Test</a>
            {% endif %}
        </div>
        </div>
    </div>
    <div class="container">
        <h1 style="margin-top: 50px; margin-bottom: 20px;"><strong>What do we provide?</strong></h1>
        <div class="card-deck">
            <div class="card">
                <img src="{% static 'authentication/game-img.png'%}" class="card-img-top" alt="..." height="230px">
                <div class="card-body">
                    <h3 class="card-title"><strong>Gamified Test</strong></h3>
                    <p class="card-text">Dyslexia screening using 32 linguistic exercises to test different cognitive skills.</p>
                </div>
            </div>
            <div class="card">
                <img src="{% static 'authentication/eye-tracking2.png'%}" class="card-img-top" alt="..." height="230px">
                <div class="card-body">
                    <h3 class="card-title"><strong>Eye Tracking</strong></h3>
                    <p class="card-text">Dyslexia screening by tracking raw eye movements using seeso eye tracker on webcam.</p>
                </div>
            </div>
            <div class="card">
                <img src="{% static 'authentication/Adaptation.png'%}" class="card-img-top" alt="..." height="230px">
                <div class="card-body">
                    <h3 class="card-title"><strong>Adaptation</strong></h3>
                    <p class="card-text"> Enhance reading experience for dyslexics by offering a browser extension that adjusts webpage content settings for a better browsing experience.</p>
                </div>
            </div>
        </div>
    </div>
    <hr>
    <div class="container">
        <div class="row">
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title"><strong>For Parents</strong></h3>
                        <p class="card-text">You can assess you child's learning abilities and know whether he is at risk of dyslexia or not ,
                            through a fun game, withot having to go to a speacialist.
                            Your child will overcome his difficulties in reading through our provided adaptive tools.
                        </p>
                        <a href="#" class="btn btn-primary">Learn more</a>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <h3 class="card-title"><strong>For Schools</strong></h3>
                        <p class="card-text">We offer a cutting-edge and scientifically validated early dyslexia screening solution to eliminate school failure due to reading-writing difficulties.
                            You will optimize the center's resources, through the automatic customization of exercises.</p>
                        <a href="#" class="btn btn-primary">Learn more</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{%endblock%}

authentication/templates/authentication/navbar.html
{%load static%}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">
        <img src="{% static 'gamified_test/logo_navy.png' %}" alt="Logo" width="30" height="26" class="d-inline-block align-text-top">
        <strong>Dyadapt</strong>
    </a>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="nav justify-content-center">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'authentication:home' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        {% if not user.is_authenticated %}
        <li class="nav-item">
            <a class="nav-link" href="{% url 'authentication:signin' %}">Sign In <span class="sr-only">(current)</span></a>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
            <a class="btn btn-outline-primary" href="{% url 'authentication:register' %}" role="button">Create an account</a>
        </li>
       </ul>
        {% else%}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">Logout <span class="sr-only">(current)</span></a>
          </li>
         </ul>
          {% endif %}
    </div>
</nav>

authentication/templates/authentication/parent-teacher-form.html
<form method="POST" action="{% url 'authentication:register-parent-teacher' %}">
    {%csrf_token%}
    <div class="form-group">
        {{ userForm.username.label_tag }}
        {{ userForm.username}}
    </div>
    <div class="form-group">
        {{ userForm.email.label_tag }}
        {{ userForm.email}}
    </div>
    <div class="form-group">
        {{ userForm.password.label_tag }}
        {{ userForm.password}}
    </div>
    <div class="form-group">
        <label for="nationalId">National Id</label>
        {{ parent_teacherForm.nationalId}}
    </div>
    <button type="submit" class="btn btn-primary">Sign up</button>
</form>

authentication/templates/authentication/player-form.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <form enctype="multipart/form-data" method="POST" action="{% url 'authentication:register-player' %}">
    {%csrf_token%}
      <div class="form-row">
          <div class="form-group col-md-12">
            {{ userForm.username.label_tag }}
            {{ userForm.username}}
            <small id="usernameHelp" class="form-text text-muted">Write your username without whitespaces.</small>
          </div>
        <div class="form-group col-md-6">
          {{ userForm.email.label_tag }}
          {{ userForm.email}}
        </div>
        <div class="form-group col-md-6">
          {{ userForm.password.label_tag }}
          {{ userForm.password}}
        </div>
      </div> 
      <div class="form-row">
          <div class="form-group col-md-5">
              <label for="isNative">Is English your native language?</label>
              {{ playerForm.isNative}}
          </div>
          <div class="form-group col-md-7">
              <label for="failedLang">Do you have difficulties in language class?</label>
              {{ playerForm.failedLang}}
          </div>
      </div>
      <div class="form-row">
          <div class="form-group col-md-5">
              <label for="nationalId">National Id</label>
              {{ playerForm.nationalId}}
          </div>
          <div class="form-group col-md-5">
              <label for="gender">Gender</label>
              {{ playerForm.gender}}
          </div>
          <div class="form-group col-md-2">
              <label for="age">Age</label>
              {{ playerForm.age}}
          </div>
      </div>
       <button type="submit" class="btn btn-primary">Sign up</button>
  </form>
</body>
</html>

authentication/templates/authentication/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Include Bootstrap css -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'authentication/css/register.css' %}">
</head>
<body>
    <div class="container custom-container">
        <div class="card custom-card mb-3">
            <div class="row no-gutters">
                <div class="col-md-6">
                    <img class="card-img" src="{% static 'authentication/dyadapt.png'%}" alt="...">
                </div>
                <div class="col-md-6">
                    <div class="card-body">
                        <h4 class="card-title">Create an account as:</h4>
                        <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
                            <li class="nav-item" role="presentation">
                                <button class="nav-link active" id="pills-player-tab" data-toggle="pill" data-target="#pills-player" type="button" role="tab" aria-controls="pills-player" aria-selected="true">Player</button>
                            </li>
                            <li class="nav-item" role="presentation">
                                <button class="nav-link" id="pills-parent/teacher-tab" data-toggle="pill" data-target="#pills-parent-teacher" type="button" role="tab" aria-controls="pills-parent/teacher" aria-selected="false">Parent /Teacher</button>
                            </li>
                        </ul>
                        <div class="tab-content" id="pills-tabContent">
                            <div class="tab-pane fade show active" id="pills-player" role="tabpanel" aria-labelledby="pills-player-tab">
                               {%include 'authentication/player-form.html'%}
                            </div>
                            <div class="tab-pane fade" id="pills-parent-teacher" role="tabpanel" aria-labelledby="pills-parent-teacher-tab">
                                {%include 'authentication/parent-teacher-form.html'%}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Include jquery -->
    <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
    <!-- Include Bootstrap JavaScript -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

authentication/templates/authentication/signin.html
{%extends "authentication/base.html"%}

{%block content%}
    <style>
        body{
            background-color: rgba(236, 237, 237, 0.187);
        }
        .card{
            box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1); /* Add shadow effect */
        }
    </style>
    <div class="container">
        <div class="card w-55">
            <div class="card-body">
              <h1 class="card-title"><strong>Sign in</strong></h1>
              <form action="{% url 'authentication:user_login' %}" method="POST">
                {%csrf_token%}
                <div class="form-group">
                  <label for="user">Username</label>
                  <input type="text" class="form-control" id="username" name="username">
                </div>
                <div class="form-group">
                  <label for="password">Password</label>
                  <input type="password" class="form-control" id="password" name="password">
                </div>
                <div class="form-group form-check">
                  <input type="checkbox" class="form-check-input" id="checkbox">
                  <label class="form-check-label" for="checkbox">Remember Me</label>
                </div>
                <button type="submit" class="btn btn-primary">Sign In</button>
              </form>
            </div>
          </div>
          </div>
      </div>
{%endblock%}