adaptation/urls.py
from django.urls import path,re_path
from . import views

app_name = 'adaptation'
urlpatterns = [
    path('', views.base, name='base'), #for startTracking
    path('bg_extension1/',views.bg_extension1, name='bg_extension1'),
    path('bg_extension2/',views.bg_extension2, name='bg_extension2'),
    path('bg_extension3/',views.bg_extension3, name='bg_extension3'),
    path('bg_extension4/',views.bg_extension4, name='bg_extension4'),

    path('font_type_extension1/',views.font_type_extension1, name='font_type_extension1'),
    path('font_type_extension2/',views.font_type_extension2, name='font_type_extension2'),
    path('font_type_extension3/',views.font_type_extension3, name='font_type_extension3'),
    path('font_type_extension4/',views.font_type_extension4, name='font_type_extension4'),
    path('font_type_extension5/',views.font_type_extension5, name='font_type_extension5'),
    path('font_type_extension6/',views.font_type_extension6, name='font_type_extension6'),
    path('font_type_extension7/',views.font_type_extension7, name='font_type_extension7'),

    path('text_color_extension/',views.text_color_extension, name='text_color_extension'),

    path('char_spacing_extension1/',views.char_spacing_extension1, name='char_spacing_extension1'),
    path('char_spacing_extension2/',views.char_spacing_extension2, name='char_spacing_extension2'),

    path('stopTracking/',views.stopTracking, name='stopTracking'),

    path('adaptation_result/',views.adaptation_result, name='adaptation_result'),

    re_path(r'.*save_gaze_data/$', views.save_gaze_data, name='save_gaze_data'),

]

dyslexia_project/urls.py
from django.contrib import admin
from django.urls import path,include
from authentication import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('test/', include('gamified_test.urls' , namespace='gamified_test')),
    path('authentication/', include('authentication.urls' , namespace= 'authentication')),
    path('eyeTracking/', include('eyeTracking.urls' , namespace= 'eyeTracking')),
    path('adaptation/', include('adaptation.urls' , namespace= 'adaptation')),
    path('logout/', views.user_logout, name='logout'),
]

eyeTracking/urls.py
from django.urls import path
from . import views

app_name = 'eyeTracking'
urlpatterns = [
    path('', views.eyeTracking, name='eyeTracking'), #for startTracking
    path('stopTracking', views.stopTracking, name='stopTracking'),
    path('save_gaze_data/', views.save_gaze_data, name='save_gaze_data'),
    path('result/', views.result, name='result'),
]

eyeTracking/models.py
from django.db import models
from authentication.models import Player

class GazeData(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    player = models.OneToOneField(Player , on_delete=models.CASCADE,null=True)
    # eye movement features
    avg_fix_duration = models.FloatField(default=0.0 , max_length=50)
    avg_saccade_duration = models.FloatField(default=0.0 , max_length=50)   
    total_fixations = models.IntegerField(default=0 , max_length=50)    #gazeInfo.y
    total_saccades = models.IntegerField(default=0 , max_length=50)
    saccades_to_fixations = models.FloatField(default=0.0 , max_length=50)
    result = models.CharField(max_length = 50 , default=" ")

    def __str__(self):
        return f'player ({self.player.user.username if self.player else "No Player"})'
    

eyeTracking/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from .models import GazeData
from gamified_test.models import Player
from django.contrib.auth.models import User
from django.http import JsonResponse
import numpy as np
import json
import pickle
import os
from .data_algorithms.ivt_algorithm import process_gaze_info

def eyeTracking(request):
    return render(request , 'eyeTracking/eyeTracking.html')
def stopTracking(request):
    return render(request , 'eyeTracking/stopTracking.html')
@csrf_exempt  # Disable CSRF protection for this view (for simplicity)
def save_gaze_data(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            gaze_data_array = data.get('gazeData', [])

            features = process_gaze_info(gaze_data_array)
            print(features)

            username = request.user.username
            user, created = User.objects.get_or_create(username=username, defaults={'password': request.user.password})
            if created:
                # Set the password using set_password to ensure it is hashed
                user.set_password(request.user.password)
                user.save()
            
            # Get or create a player and associate with the user
            player, created = Player.objects.get_or_create(user=user)

            # Get or create GazeData object for the player
            gaze_data, created = GazeData.objects.get_or_create(player=player)

            # Set features
            gaze_data.avg_fix_duration = features['Average Fixation Duration']
            gaze_data.avg_saccade_duration = features['Average Saccade Duration']
            gaze_data.total_fixations = features['Total Fixations']
            gaze_data.total_saccades = features['Total Saccades']
            gaze_data.saccades_to_fixations = features['ratio']

            # store data in model
            gaze_data.save()

            return JsonResponse({'status': 'success'}, status=200)
        except json.JSONDecodeError as e:
            print("JSON decode error:", e)
            return JsonResponse({'error': 'Invalid JSON'}, status=400)
    else:
        return JsonResponse({'status': 'error', 'message': 'Invalid request method'}, status=405)

def getPredictions(data_array):
    # Load the ML model 
    current_directory = os.path.dirname(os.path.abspath(__file__))
    model_file_path = os.path.join(current_directory, 'ml_model', 'eyetracking_model.sav')
    scaler_file_path = os.path.join(current_directory, 'ml_model', 'scaler.sav')
    
    with open(model_file_path, "rb") as model_file:
        model = pickle.load(model_file)
    
    with open(scaler_file_path, "rb") as scaler_file:
        scaler = pickle.load(scaler_file)
    
    # Scale the input data using the loaded scaler
    scaled_data = scaler.transform([data_array])
    prediction = model.predict(scaled_data)
    
    if prediction == 0:
        return "Low-Risk"  # Not dyslexic
    elif prediction == 1:
        return "High-Risk"  # Dyslexic
    else:
        return "error"
        
# result page view
def result(request):
    # Define the order of fields for feeding into the ML model
    field_order = [
        'Gender','Avg_Fix_Duration', 'Avg_Sacc_Duration', 'Total_Fix', 'Total_Sacc','Sacc_Fix_Ratio'
    ]
 
    data_dict = {}
    username = request.user.username
    user, created = User.objects.get_or_create(username=username, defaults={'password': request.user.password})
    if created:
        # Set the password using set_password to ensure it is hashed
        user.set_password(request.user.password)
        user.save()
    
    # Get or create a player and associate with the user
    player, created = Player.objects.get_or_create(user=user)

    # Get or create GazeData object for the player
    gaze_data_instance, created = GazeData.objects.get_or_create(player=player)
    
    # Access data of player
    gender = gaze_data_instance.player.gender
    created_at = gaze_data_instance.created_at
    data_dict['Gender'] = 1 if gender.lower() == 'male' else 0
    data_dict['Avg_Fix_Duration'] = gaze_data_instance.avg_fix_duration
    data_dict['Avg_Sacc_Duration'] = gaze_data_instance.avg_saccade_duration
    data_dict['Total_Fix'] = gaze_data_instance.total_fixations
    data_dict['Total_Sacc'] = gaze_data_instance.total_saccades
    data_dict['Sacc_Fix_Ratio'] = gaze_data_instance.saccades_to_fixations
    
    # Arrange the data according to the specified order
    input_data = [data_dict[field] for field in field_order]
    data_array = np.array(input_data, dtype=float)  

    result = getPredictions(data_array)
    
    # Save result in database
    setattr(gaze_data_instance, 'result', result)
    gaze_data_instance.save()

    return render(request, 'eyeTracking/result.html', 
                  {'result': result ,
                   'date': created_at})

eyeTracking/templates/eyeTracking/eyeTracking.html
{% block content %}
{% load static %}
<head>
  <meta charset="utf-8">
  <title>Eye Tracking Test</title>
  <!-- Include jquery -->
  <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script>
  <!-- Bootstrap Documentation Links -->
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
  <style>
    body, html {
        height: 100%;
        margin: 0;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
    .container {
        font-size: xx-large;
        font-family: Arial;
        line-height: 1.7;
        flex: 1;
        display: flex;
        align-items: center;
        justify-content: flex-start; /* Align items to the start */
        text-align: left; /* Ensure text is left-aligned */
        padding: 20px;
        width: 100%; /* Adjust width as needed */
    }
    .bottom-container {
      display: flex;
      flex-direction: row;
      position: fixed;
      bottom: 20px;
      left: 50%;
      transform: translateX(-50%);
      z-index: 1000;
    }
    #calibrationButton, #stopTrackingButton {
      margin-top:500px;
        margin:5px;
        width: 200px;
        height:auto;
    }
    #embeddedPage {
      position: fixed;
      bottom: 20px;
      left: 50%;
      transform: translateX(-50%);
      width: 100px;
      height: 100px;
      border: none;
  }
    @media (max-width: 600px) {
        #calibrationButton, #stopTrackingButton {
            width: 90%;
            margin: 10px 0;
        }
        .container {
            width: 90%;
            font-size: large;
        }
    }
  </style>
</head>
<body>
  <canvas id="output" style="position: fixed;"></canvas>
  <div class="container">
    <p>The sun was bright. They went to the park.<br>
<<<<<<< HEAD
      There was a dinosaur statue.<br> 
      Tom said, "Look here." Sara saw a hole.<br>
      She gave a laugh.<br> "Is it real?" she asked.<br> 
      They walked further along.<br> 
      They found a hidden path.<br> 
=======
      There was a dinosaur statue.<br>
      Tom said, "Look here." Sara saw a hole.<br>
      She gave a laugh.<br> "Is it real?" she asked.<br>
      They walked further along.<br>
      They found a hidden path.<br>
>>>>>>> 129c61f130de938c464386fd46624d43b338b7a0
      It was an exciting day.</p>
  </div>
  <div class="bottom-container">
    <button id="calibrationButton" type="button" class="btn btn-primary">Start calibration</button>
    <button id="stopTrackingButton" type="button" class="btn btn-primary">Finish</button>
  </div>
  <script src="{% static 'eyeTracking/js/eyeTracking.js' %}" type="module" id="myScript" data-url="{% url 'eyeTracking:result' %}"></script>
</body>
<<<<<<< HEAD
{% endblock %}
=======
{% endblock %}
>>>>>>> 129c61f130de938c464386fd46624d43b338b7a0

eyeTracking/templates/eyeTracking/result.html
{% extends "authentication/base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'eyeTracking/css/result.css' %}">
    <div class="container">
        <div class="card w-55">
            <div class="card-body">
                <h1 class="card-title"><strong>Dyadapt Eye Tracking Screening Test</strong></h1>
                <p class="date">Date:    {{ date }}</p> 
                <div class="result">{{ result }}</div>
                <div class="adaptation-container">
                    <p>Do you want reading to be easier?</p>
                    <a class="btn btn-primary btn-lg" href="{% url 'adaptation:base' %}" id="adaptationBtn" role="button">Go to adaptation</a>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

eyeTracking/templates/eyeTracking/stopTracking.html
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <!-- Bootstrap Documentation Links -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</head>
<style>
    body, html {
        height: 100%;
        margin: 0;
        display: flex;
        justify-content: center;
        align-items: center;
    }
    .container {
        text-align: center;
        font-size: larger;
        line-height: 2.0;
        flex-grow: 1;
    }
</style>
<body>
    <div class="container">
        <button type="button" id="stopTrackingButton" class="btn btn-primary">Finish</button>
    </div>
</body>