adaptation/urls.py
from django.urls import path,re_path
from . import views

app_name = 'adaptation'
urlpatterns = [
    path('', views.base, name='base'), #for startTracking
    path('bg_extension1/',views.bg_extension1, name='bg_extension1'),
    path('bg_extension2/',views.bg_extension2, name='bg_extension2'),
    path('bg_extension3/',views.bg_extension3, name='bg_extension3'),
    path('bg_extension4/',views.bg_extension4, name='bg_extension4'),

    path('font_type_extension1/',views.font_type_extension1, name='font_type_extension1'),
    path('font_type_extension2/',views.font_type_extension2, name='font_type_extension2'),
    path('font_type_extension3/',views.font_type_extension3, name='font_type_extension3'),
    path('font_type_extension4/',views.font_type_extension4, name='font_type_extension4'),
    path('font_type_extension5/',views.font_type_extension5, name='font_type_extension5'),
    path('font_type_extension6/',views.font_type_extension6, name='font_type_extension6'),
    path('font_type_extension7/',views.font_type_extension7, name='font_type_extension7'),

    path('text_color_extension/',views.text_color_extension, name='text_color_extension'),

    path('char_spacing_extension1/',views.char_spacing_extension1, name='char_spacing_extension1'),
    path('char_spacing_extension2/',views.char_spacing_extension2, name='char_spacing_extension2'),

    path('stopTracking/',views.stopTracking, name='stopTracking'),

    path('adaptation_result/',views.adaptation_result, name='adaptation_result'),

    re_path(r'.*save_gaze_data/$', views.save_gaze_data, name='save_gaze_data'),

]

dyslexia_project/urls.py
from django.contrib import admin
from django.urls import path,include
from authentication import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('test/', include('gamified_test.urls' , namespace='gamified_test')),
    path('authentication/', include('authentication.urls' , namespace= 'authentication')),
    path('eyeTracking/', include('eyeTracking.urls' , namespace= 'eyeTracking')),
    path('adaptation/', include('adaptation.urls' , namespace= 'adaptation')),
    path('logout/', views.user_logout, name='logout'),
]

eyeTracking/urls.py
from django.urls import path
from . import views

app_name = 'eyeTracking'
urlpatterns = [
    path('', views.eyeTracking, name='eyeTracking'), #for startTracking
    path('stopTracking', views.stopTracking, name='stopTracking'),
    path('save_gaze_data/', views.save_gaze_data, name='save_gaze_data'),
    path('result/', views.result, name='result'),
]

adaptation/models.py
from django.db import models
from django.contrib.auth.models import User

class adaptation_GazeData(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,null=True)
    base_afd = models.FloatField(null=True, blank=True)
    min_bg_color = models.CharField(max_length=50, null=True, blank=True)
    min_bg_color_afd = models.FloatField(null=True, blank=True)
    min_font_type = models.CharField(max_length=50, null=True, blank=True)
    min_font_type_afd = models.FloatField(null=True, blank=True)
    min_font_color = models.CharField(max_length=50, null=True, blank=True)
    min_font_color_afd = models.FloatField(null=True, blank=True)
    min_char_spacing = models.CharField(max_length=50, null=True, blank=True)
    min_char_spacing_afd = models.FloatField(null=True, blank=True)
    overall_gain = models.FloatField(null=True, blank=True)

    def __str__(self):
        if self.user:
            return f'User({self.user.username})'
        return f'No User Assigned'

    def calculate_overall_gain(self):
        gains = [
            self.min_bg_color_afd,
            self.min_font_type_afd,
            self.min_font_color_afd,
            self.min_char_spacing_afd
        ]
        gains = [g for g in gains if g is not None]
        return (sum(gains)/self.base_afd) / len(gains) if gains else None

eyeTracking/models.py
from django.db import models
from authentication.models import Player

class GazeData(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    player = models.OneToOneField(Player , on_delete=models.CASCADE,null=True)
    # eye movement features
    avg_fix_duration = models.FloatField(default=0.0 , max_length=50)
    avg_saccade_duration = models.FloatField(default=0.0 , max_length=50)   
    total_fixations = models.IntegerField(default=0 , max_length=50)    #gazeInfo.y
    total_saccades = models.IntegerField(default=0 , max_length=50)
    saccades_to_fixations = models.FloatField(default=0.0 , max_length=50)
    result = models.CharField(max_length = 50 , default=" ")

    def __str__(self):
        return f'player ({self.player.user.username if self.player else "No Player"})'
    

adaptation/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from .models import adaptation_GazeData
import json
from urllib.parse import urlparse
from eyeTracking.data_algorithms.ivt_algorithm import process_gaze_info

colors={
    '#ffffff':'White',
    '#edd1b0':'Peach',
    '#eddd6e':'Orange',
    '#f8fd89':'Yellow',
    '#fffdd0':'Cream',
    '#0000ff':'Blue',
    '#000000':'Black'
}

feature_files = {
    #background color files
    'bg_base':'#ffffff',
    'bg_extension1': '#edd1b0',
    'bg_extension2': '#eddd6e',
    'bg_extension3': '#f8fd89',
    'bg_extension4': '#fffdd0',

    #font type files
    'font_type_base':'Arial',
    'font_type_extension1': 'OpenDyslexic',
    'font_type_extension2': 'CMU',
    'font_type_extension3': 'Courier',
    'font_type_extension4': 'Verdana',
    'font_type_extension5': 'Helvetica',
    'font_type_extension6': 'Times',
    'font_type_extension7': 'Comic',

    #character spacing files
    'char_spacing_base': '0.1em',
    'char_spacing_extension1': '0.04em',
    'char_spacing_extension2': '0.17em',

    #text color files
    'text_color_base':'#000000',
    'text_color_extension': '#0000ff',
}

# Create your views here.
def base(request):
    return render(request , 'adaptation/base.html')
def bg_extension1(request):
    return render(request , 'adaptation/bg_extension1.html')
def bg_extension2(request):
    return render(request , 'adaptation/bg_extension2.html')
def bg_extension3(request):
    return render(request , 'adaptation/bg_extension3.html')
def bg_extension4(request):
    return render(request , 'adaptation/bg_extension4.html')

def font_type_extension1(request):
    return render(request , 'adaptation/font_type_extension1.html')
def font_type_extension2(request):
    return render(request , 'adaptation/font_type_extension2.html')
def font_type_extension3(request):
    return render(request , 'adaptation/font_type_extension3.html')
def font_type_extension4(request):
    return render(request , 'adaptation/font_type_extension4.html')
def font_type_extension5(request):
    return render(request , 'adaptation/font_type_extension5.html')
def font_type_extension6(request):
    return render(request , 'adaptation/font_type_extension6.html')
def font_type_extension7(request):
    return render(request , 'adaptation/font_type_extension7.html')

def text_color_extension(request):
    return render(request , 'adaptation/text_color_extension.html')

def char_spacing_extension1(request):
    return render(request , 'adaptation/char_spacing_extension1.html')
def char_spacing_extension2(request):
    return render(request , 'adaptation/char_spacing_extension2.html')

def stopTracking(request):
    return render(request , 'adaptation/stopTracking.html')

def adaptation_result(request):
    # Assuming you want to retrieve the data for the currently logged-in user
    user = request.user
    try:
        variations = adaptation_GazeData.objects.get(user=user)
        result = {
            'bg_color_name':colors[variations.min_bg_color],
            'font_color_name':colors[variations.min_font_color],
            'min_bg_color': variations.min_bg_color,
            'min_font_type': variations.min_font_type,
            'min_font_color': variations.min_font_color,
            'min_char_spacing': variations.min_char_spacing,
        }
    except adaptation_GazeData.DoesNotExist:
        result = {
            'bg_color_name':'N/A',
            'font_color_name':'N/A',
            'min_bg_color': 'N/A',
            'min_font_type': 'N/A',
            'min_font_color': 'N/A',
            'min_char_spacing': 'N/A',
        }
    context = {
        'result': result,
    }
    return render(request, 'adaptation/adaptation_result.html', context)

@csrf_exempt  # Disable CSRF protection for this view (for simplicity)
def save_gaze_data(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            gaze_data_array = data.get('gazeData', [])
            features = process_gaze_info(gaze_data_array)
            AFD = features['Average Fixation Duration']
            user = request.user
 
            # Get or create GazeData object for the player
            gaze_data, created = adaptation_GazeData.objects.get_or_create(user=user)
 
            # Determine the setting variation from the URL
            current_url=data.get('currentUrl','')
            # Split the URL by '/' and get the last segment
            segments = current_url.split('/')
            variation = segments[-2]  # Get the second last segment
            print('Variation:', variation)
            
           
            if variation == 'adaptation':
                # Base page
                gaze_data.base_afd = AFD
                gaze_data.min_bg_color=feature_files['bg_base']
                gaze_data.min_bg_color_afd = AFD
                gaze_data.min_font_type =feature_files['font_type_base']
                gaze_data.min_font_type_afd = AFD
                gaze_data.min_font_color = feature_files['text_color_base']
                gaze_data.min_font_color_afd = AFD
                gaze_data.min_char_spacing = feature_files['char_spacing_base']
                gaze_data.min_char_spacing_afd = AFD
                print('Base AFD:',AFD)

            elif 'bg_extension' in variation:
                print('before check Bg Filename:',variation)
                print('before check Bg AFD:',AFD)
                if gaze_data.min_bg_color_afd is None or AFD < gaze_data.min_bg_color_afd:
                    gaze_data.min_bg_color = feature_files[variation]
                    gaze_data.min_bg_color_afd = AFD
                    print('Bg Filename:',variation)
                    print('Bg AFD:',AFD)
            elif 'font_type_extension' in variation:
                if gaze_data.min_font_type_afd is None or AFD < gaze_data.min_font_type_afd:
                    gaze_data.min_font_type = feature_files[variation]
                    gaze_data.min_font_type_afd = AFD
                    print('Font type Filename:',variation)
                    print('Font type AFD:',AFD)
            elif 'text_color_extension' in variation:
                if gaze_data.min_font_color_afd is None or AFD < gaze_data.min_font_color_afd:
                    gaze_data.min_font_color = feature_files[variation]
                    gaze_data.min_font_color_afd = AFD
                    print('Text color Filename:',variation)
                    print('Text color AFD:',AFD)
            elif 'char_spacing_extension' in variation:
                if gaze_data.min_char_spacing_afd is None or AFD < gaze_data.min_char_spacing_afd:
                    gaze_data.min_char_spacing = feature_files[variation]
                    gaze_data.min_char_spacing_afd = AFD
                    print('Character Spacing Filename:',variation)
                    print('Character Spacing AFD:',AFD)
 
            # Calculate overall gain
            gaze_data.overall_gain = gaze_data.calculate_overall_gain()
            print('Gain:',gaze_data.overall_gain)

            # Save the updated gaze data
            gaze_data.save()
 
            return JsonResponse({'status': 'success', 'avg_fix_duration': AFD}, status=200)
        except json.JSONDecodeError as e:
            return JsonResponse({'error': 'Invalid JSON'}, status=400)
        except Exception as e:
            return JsonResponse({'error': str(e)}, status=500)
    else:
        return JsonResponse({'status': 'error', 'message': 'Invalid request method'}, status=405)


    

eyeTracking/views.py
from django.shortcuts import render
from django.views.decorators.csrf import csrf_exempt
from .models import GazeData
from gamified_test.models import Player
from django.contrib.auth.models import User
from django.http import JsonResponse
import numpy as np
import json
import pickle
import os
from .data_algorithms.ivt_algorithm import process_gaze_info

def eyeTracking(request):
    return render(request , 'eyeTracking/eyeTracking.html')
def stopTracking(request):
    return render(request , 'eyeTracking/stopTracking.html')
@csrf_exempt  # Disable CSRF protection for this view (for simplicity)
def save_gaze_data(request):
    if request.method == 'POST':
        try:
            data = json.loads(request.body)
            gaze_data_array = data.get('gazeData', [])

            features = process_gaze_info(gaze_data_array)
            print(features)

            username = request.user.username
            user, created = User.objects.get_or_create(username=username, defaults={'password': request.user.password})
            if created:
                # Set the password using set_password to ensure it is hashed
                user.set_password(request.user.password)
                user.save()
            
            # Get or create a player and associate with the user
            player, created = Player.objects.get_or_create(user=user)

            # Get or create GazeData object for the player
            gaze_data, created = GazeData.objects.get_or_create(player=player)

            # Set features
            gaze_data.avg_fix_duration = features['Average Fixation Duration']
            gaze_data.avg_saccade_duration = features['Average Saccade Duration']
            gaze_data.total_fixations = features['Total Fixations']
            gaze_data.total_saccades = features['Total Saccades']
            gaze_data.saccades_to_fixations = features['ratio']

            # store data in model
            gaze_data.save()

            return JsonResponse({'status': 'success'}, status=200)
        except json.JSONDecodeError as e:
            print("JSON decode error:", e)
            return JsonResponse({'error': 'Invalid JSON'}, status=400)
    else:
        return JsonResponse({'status': 'error', 'message': 'Invalid request method'}, status=405)

def getPredictions(data_array):
    # Load the ML model 
    current_directory = os.path.dirname(os.path.abspath(__file__))
    model_file_path = os.path.join(current_directory, 'ml_model', 'eyetracking_model.sav')
    scaler_file_path = os.path.join(current_directory, 'ml_model', 'scaler.sav')
    
    with open(model_file_path, "rb") as model_file:
        model = pickle.load(model_file)
    
    with open(scaler_file_path, "rb") as scaler_file:
        scaler = pickle.load(scaler_file)
    
    # Scale the input data using the loaded scaler
    scaled_data = scaler.transform([data_array])
    prediction = model.predict(scaled_data)
    
    if prediction == 0:
        return "Low-Risk"  # Not dyslexic
    elif prediction == 1:
        return "High-Risk"  # Dyslexic
    else:
        return "error"
        
# result page view
def result(request):
    # Define the order of fields for feeding into the ML model
    field_order = [
        'Gender','Avg_Fix_Duration', 'Avg_Sacc_Duration', 'Total_Fix', 'Total_Sacc','Sacc_Fix_Ratio'
    ]
 
    data_dict = {}
    username = request.user.username
    user, created = User.objects.get_or_create(username=username, defaults={'password': request.user.password})
    if created:
        # Set the password using set_password to ensure it is hashed
        user.set_password(request.user.password)
        user.save()
    
    # Get or create a player and associate with the user
    player, created = Player.objects.get_or_create(user=user)

    # Get or create GazeData object for the player
    gaze_data_instance, created = GazeData.objects.get_or_create(player=player)
    
    # Access data of player
    gender = gaze_data_instance.player.gender
    created_at = gaze_data_instance.created_at
    data_dict['Gender'] = 1 if gender.lower() == 'male' else 0
    data_dict['Avg_Fix_Duration'] = gaze_data_instance.avg_fix_duration
    data_dict['Avg_Sacc_Duration'] = gaze_data_instance.avg_saccade_duration
    data_dict['Total_Fix'] = gaze_data_instance.total_fixations
    data_dict['Total_Sacc'] = gaze_data_instance.total_saccades
    data_dict['Sacc_Fix_Ratio'] = gaze_data_instance.saccades_to_fixations
    
    # Arrange the data according to the specified order
    input_data = [data_dict[field] for field in field_order]
    data_array = np.array(input_data, dtype=float)  

    result = getPredictions(data_array)
    
    # Save result in database
    setattr(gaze_data_instance, 'result', result)
    gaze_data_instance.save()

    return render(request, 'eyeTracking/result.html', 
                  {'result': result ,
                   'date': created_at})

adaptation/templates/adaptation/bg_extension1.html
<!DOCTYPE html>
{%extends "adaptation/base.html"%}
{%load static%}
{%block content%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <style>
     body, html {
        background-color: #edd1b0;
        font-size: xx-large;
    }
    #calibrationButton {
        display: none;
    }
  </style>
  <body>
      <p>Inside the old house, a mysterious box sat on shelves filled with dusty books. </br>
        The computer beside it blinked with messages.  "What could be in there?" he wondered aloud.</br>  
        He approached the box, curious.  Meanwhile, a beautiful doctor in town read a biography of </br>
        a famous zookeeper, fascinated by their marvelous experiences with exotic animals. </br>       
    {% block scripts %}
    <script src="{%static 'adaptation/js/eyeTracking.js'%}" type="module"
   id="myScript" data-url="{% url 'adaptation:bg_extension2' %}"></script>
  {% endblock %}
    
    {%endblock%}
  </body>
</html>

adaptation/templates/adaptation/bg_extension2.html
<!DOCTYPE html>
{%extends "adaptation/base.html"%}
{%load static%}
{%block content%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <style>
     body, html {
        background-color: #eddd6e;
        font-size: xx-large;
    }
    #calibrationButton {
        display: none;
    }
  </style>
  <body>
      Far away, a train chugged through a dense forest.  On board, a little panda peeked</br>
      through a window, seeing rainbows glistening beautifully after the rain. "This is an </br>
      incredible adventure," said the zookeeper, who gently held the panda. They were happily </br>
      heading to a new school where nature was the primary language taught to everyone.</br>
    {% block scripts %}
    <script src="{%static 'adaptation/js/eyeTracking.js'%}" type="module"
   id="myScript" data-url="{% url 'adaptation:bg_extension3' %}"></script>
  {% endblock %}
    {%endblock%}
  </body>
</html>

adaptation/templates/adaptation/bg_extension3.html
<!DOCTYPE html>
{%extends "adaptation/base.html"%}
{%load static%}
{%block content%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <style>
     body, html {
        background-color: #f8fd89;
    }
    .container {
        background-color: #f8fd89;
    }
    #calibrationButton {
        display: none;
    }
  </style>
  <body>
    <div class="container">
      On Friday, the farmer decided to visit the town.He walked</br>
       down the busy streets, buying bread and plums. He saw a doctor</br>
       who looked upset. "Are you alright?" he asked kindly.</br>
      She smiled weakly, "I am fine, just tired from a difficult trial."  </br>
      They talked for a while, sharing stories and helpful advice.
      
        </br></div>
    {% block scripts %}
    <script src="{%static 'adaptation/js/eyeTracking.js'%}" type="module"
   id="myScript" data-url="{% url 'adaptation:bg_extension4' %}"></script>
  {% endblock %}
    {%endblock%}
  </body>
</html>

adaptation/templates/adaptation/bg_extension4.html
<!DOCTYPE html>
{%extends "adaptation/base.html"%}
{%load static%}
{%block content%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <style>
     body, html {
        background-color:#fffdd0;
        font-size: xx-large;

    }
    #calibrationButton {
        display: none;
    }
  </style>
  <body>
      A robot rolled by, adding to the town's excitement.  "I have never seen one up </br>
      close before," the farmer admitted. The doctor laughed, "They are quite common </br>
      here now." As the tired farmer gratefully returned home,  he felt a sense of </br>
      fulfilment and happiness. "That was a good day," he said, opening the wooden door.</br>
    {% block scripts %}
    <script src="{%static 'adaptation/js/eyeTracking.js'%}" type="module"
   id="myScript" data-url="{% url 'adaptation:font_type_extension1' %}"></script>
  {% endblock %}
    {%endblock%}
  </body>
</html>

adaptation/templates/adaptation/char_spacing_extension1.html
<!DOCTYPE html>
{%extends "adaptation/base.html"%}
{%load static%}
{%block content%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <style>
    body, html {
        letter-spacing: 0.04em;
        font-size: xx-large;
    }
    #calibrationButton {
        display: none;
    }
  </style>
  <body>
    The book became a bestseller. People from all over came to hear his inspiring story.</br>
    The farmer felt a sense of fulfilment and happiness he had never known. His adventure </br>
    had brought him not just excitement, but also a deeper understanding of himself and </br>
    the world. Each handshake and smile affirmed his journey's incredible impact.</br>
    
    {% block scripts %}
    <script src="{%static 'adaptation/js/eyeTracking.js'%}" type="module"
   id="myScript" data-url="{% url 'adaptation:char_spacing_extension2' %}"></script>
  {% endblock %}

    {%endblock%}
  </body>
</html>

adaptation/templates/adaptation/char_spacing_extension2.html
<!DOCTYPE html>
{%extends "adaptation/base.html"%}
{%load static%}
{%block content%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <style>
    body, html {
        letter-spacing: 0.17em;
    }
    #calibrationButton {
        display: none;
    }
  </style>
  <body>
    He continued to live in his house, tending to his farm. But now, he had a new</br>
    purpose. Every Wednesday, he would sit by the window, looking at the rainbow</br> 
    after the rain and write. His life was filled with stories and new adventures.</br> 
    Occasionally, he would visit the nearby town for supplies and inspiration.</br>
    
    {% block scripts %}
    <script src="{%static 'adaptation/js/eyeTracking.js'%}" type="module"
   id="myScript" data-url="{% url 'adaptation:adaptation_result' %}"></script>
  {% endblock %}

    {%endblock%}
  </body>
</html>

adaptation/templates/adaptation/eyeTracking.html
<!doctype html>
<html class="no-js" lang="">
{% load static %}
<head>
  <meta charset="utf-8">
  <title>Eye Tracking Test</title>
  <style>
    body, html {
        height: 100%;
        margin: 0;
        display: flex;
        flex-direction: column;
        justify-content: center;
        align-items: center;
    }
    .container {
         /* padding: 0 5%; Add padding from the sides */
         /* text-align: justify; 
         justify-content: center;
         Justify the text */
        font-size: xx-large;
        line-height: 2.0;
        flex: 1; /* Allow the container to grow and center */
        display: flex;
        align-items: center;
    }
    #calibrationButton {
        margin-bottom: 20px; /* Add some margin from the bottom */
        position: fixed;
        bottom: 10px;
        left: 50%;
        transform: translateX(-50%);
        z-index: 1000; /* Ensure button is on top */
    }
    #embeddedPage {
        position: fixed;
        bottom: 20px;
        left: 50%;
        transform: translateX(-50%);
        width: 100px;
        height: 100px;
        border: none;
    }
  </style>
</head>
<body>
  <canvas id="output" style="position: fixed;"></canvas>
  <button id="calibrationButton">Start calibration</button>
  <div class="container">
    <p>The sun was bright.They went 
      to the park.</br> There was a 
      dinosaur statue.</br> Tom said, "Look 
      here." Sara saw a hole.</br>
      She gave a laugh.</br> "Is it 
      real?" she asked. </br>They walked 
      further along.</br> They found a hidden 
      path.</br> It was an exciting day.</div>
  <!-- Embed another HTML page containing the stopTracking button to ensure its responsiveness when eyeTracking is active -->
  <iframe id="embeddedPage" src="{% url 'eyeTracking:stopTracking' %}"></iframe>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  <script src="{% static 'eyeTracking/js/eyeTracking.js' %}" type="module"></script>
  </body>
</html>

adaptation/templates/adaptation/font_type_extension3.html
<!DOCTYPE html>
{%extends "adaptation/base.html"%}
{%load static%}
{%block content%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <style>
    @font-face {
        font-family: 'Courier';
        src: url('{% static "adaptation/fonts/CourierPrime-Regular.ttf" %}') format('truetype');
        font-weight: normal;
        font-style: normal;
    }
  
    body, html {
        font-family: 'Courier', Arial, sans-serif;
        font-size: xx-large;
    }
    #calibrationButton {
        display: none;
    }
  </style>
  <body>
    Together, they walked until they reached a jail. "The answer lies here," the </br>
    fisherman said. The farmer was hesitant but curious. Inside, he met a wise old </br>
    man who held a whole lot of knowledge. "This box will lead you to an airplane," </br>
    he explained mysteriously, pointing to the distant horizon beyond the town's limits.</br>
    
    {% block scripts %}
    <script src="{%static 'adaptation/js/eyeTracking.js'%}" type="module"
   id="myScript" data-url="{% url 'adaptation:font_type_extension4' %}"></script>
  {% endblock %}
    {%endblock%}
  </body>
</html>

adaptation/templates/adaptation/font_type_extension4.html
<!DOCTYPE html>
{%extends "adaptation/base.html"%}
{%load static%}
{%block content%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <style>
    body, html {
        font-family: Verdana; 
        font-size: xx-large;
    }
    #calibrationButton {
        display: none;
    }
  </style>
  <body>
    Confused but intrigued, the farmer left the jail.  He continued his journey, the goal </br>
    clearer now. He met a witch who could fly. "I will help you," she said, casting a</br> 
    spell that made the airplane appear. He boarded it, ready for whatever exciting </br>
    adventure came next. They flew over forests, rivers, and a rainbow.</br>
    
    
    {% block scripts %}
    <script src="{%static 'adaptation/js/eyeTracking.js'%}" type="module"
   id="myScript" data-url="{% url 'adaptation:font_type_extension5' %}"></script>
  {% endblock %}

    {%endblock%}
  </body>
</html>

adaptation/templates/adaptation/font_type_extension5.html
<!DOCTYPE html>
{%extends "adaptation/base.html"%}
{%load static%}
{%block content%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  </head>
  <style>
    body, html {
        font-family: Helvetica; 
        font-size: xx-large;
    }
    #calibrationButton {
        display: none;
    }
  </style>
  <body>
    High in the air, he saw the world below, marvelous and beautiful.  His destination</br> 
    was a town far away. "This is incredible," he thought, feeling happy and free.</br> 
    The airplane landed smoothly. He stepped out, ready to continue his quest.</br>
    As he walked through the town square, he noticed a rainbow arcing across the sky.</br>
    
      
    {% block scripts %}
    <script src="{%static 'adaptation/js/eyeTracking.js'%}" type="module"
   id="myScript" data-url="{% url 'adaptation:font_type_extension6' %}"></script>
  {% endblock %}

    {%endblock%}
  </body>
</html>