adaptation/urls.py
from django.urls import path,re_path
from . import views

app_name = 'adaptation'
urlpatterns = [
    path('', views.base, name='base'), #for startTracking
    path('bg_extension1/',views.bg_extension1, name='bg_extension1'),
    path('bg_extension2/',views.bg_extension2, name='bg_extension2'),
    path('bg_extension3/',views.bg_extension3, name='bg_extension3'),
    path('bg_extension4/',views.bg_extension4, name='bg_extension4'),

    path('font_type_extension1/',views.font_type_extension1, name='font_type_extension1'),
    path('font_type_extension2/',views.font_type_extension2, name='font_type_extension2'),
    path('font_type_extension3/',views.font_type_extension3, name='font_type_extension3'),
    path('font_type_extension4/',views.font_type_extension4, name='font_type_extension4'),
    path('font_type_extension5/',views.font_type_extension5, name='font_type_extension5'),
    path('font_type_extension6/',views.font_type_extension6, name='font_type_extension6'),
    path('font_type_extension7/',views.font_type_extension7, name='font_type_extension7'),

    path('text_color_extension/',views.text_color_extension, name='text_color_extension'),

    path('char_spacing_extension1/',views.char_spacing_extension1, name='char_spacing_extension1'),
    path('char_spacing_extension2/',views.char_spacing_extension2, name='char_spacing_extension2'),

    path('stopTracking/',views.stopTracking, name='stopTracking'),

    path('adaptation_result/',views.adaptation_result, name='adaptation_result'),

    re_path(r'.*save_gaze_data/$', views.save_gaze_data, name='save_gaze_data'),

]

dyslexia_project/urls.py
from django.contrib import admin
from django.urls import path,include
from authentication import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin/', admin.site.urls),
    path('test/', include('gamified_test.urls' , namespace='gamified_test')),
    path('authentication/', include('authentication.urls' , namespace= 'authentication')),
    path('eyeTracking/', include('eyeTracking.urls' , namespace= 'eyeTracking')),
    path('adaptation/', include('adaptation.urls' , namespace= 'adaptation')),
    path('logout/', views.user_logout, name='logout'),
]

eyeTracking/urls.py
from django.urls import path
from . import views

app_name = 'eyeTracking'
urlpatterns = [
    path('', views.eyeTracking, name='eyeTracking'), #for startTracking
    path('stopTracking', views.stopTracking, name='stopTracking'),
    path('save_gaze_data/', views.save_gaze_data, name='save_gaze_data'),
    path('result/', views.result, name='result'),
]

gamified_test/urls.py
from django.urls import path
from . import views

app_name = 'gamified_test'

urlpatterns = [
    path('signin/', views.signin, name='signin'),
    path('register/', views.register, name='register'),
    path('q1Screen/', views.q1Screen, name='q1Screen'),
    path('q2Screen/', views.q2Screen, name='q2Screen'),
    path('q3Screen/', views.q3Screen, name='q3Screen'),
    path('q4Screen/', views.q4Screen, name='q4Screen'),
    path('q5Screen/', views.q5Screen, name='q5Screen'),
    path('q6Screen/', views.q6Screen, name='q6Screen'),
    path('q7Screen/', views.q7Screen, name='q7Screen'),
    path('q8Screen/', views.q8Screen, name='q8Screen'),
    path('q9Screen/', views.q9Screen, name='q9Screen'),
    path('q10Screen/', views.q10Screen, name='q10Screen'),
    path('q11Screen/', views.q11Screen, name='q11Screen'),
    path('q12Screen/', views.q12Screen, name='q12Screen'),
    path('q13Screen/', views.q13Screen, name='q13Screen'),
    path('q14Screen/', views.q14Screen, name='q14Screen'),
    path('q15Screen/', views.q15Screen, name='q15Screen'),
    path('q16Screen/', views.q16Screen, name='q16Screen'),
    path('q17Screen/', views.q17Screen, name='q17Screen'),
    path('q18Screen/', views.q18Screen, name='q18Screen'),
    path('q19Screen/', views.q19Screen, name='q19Screen'),
    path('q20Screen/', views.q20Screen, name='q20Screen'),
    path('q21Screen/', views.q21Screen, name='q21Screen'),
    path('q22Screen/', views.q22Screen, name='q22Screen'),
    path('q23Screen/', views.q23Screen, name='q23Screen'),
    path('q24Screen/', views.q24Screen, name='q24Screen'),
    path('q25Screen/', views.q25Screen, name='q25Screen'),
    path('q26Screen/', views.q26Screen, name='q26Screen'),
    path('q27Screen/', views.q27Screen, name='q27Screen'),
    path('q28Screen/', views.q28Screen, name='q28Screen'),
    path('q29Screen/', views.q29Screen, name='q29Screen'),
    path('q30Screen/', views.q30Screen, name='q30Screen'),
    path('q31Screen/', views.q31Screen, name='q31Screen'),
    path('q32Screen/', views.q32Screen, name='q32Screen'),
    path('save_performance_data/<int:exercise_num>/', views.save_performance_data, name='save_performance_data'),
    path('result/', views.result, name='result'),
    path('statistical_result/',views.result,name='statistical_result'),
]

gamified_test/models.py
from authentication.models import Player
from django.db import models

class GameData(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    # demographic data
    player = models.OneToOneField(Player , on_delete=models.CASCADE)

    # Define dynamic fields for performance metrics of each exercise
    for i in range(1, 33):  # There are 32 exercises
        locals()[f'clicks{i}'] = models.IntegerField(default=0)
        locals()[f'hits{i}'] = models.IntegerField(default=0)
        locals()[f'misses{i}'] = models.IntegerField(default=0)
        locals()[f'missrate{i}'] = models.FloatField(default=0.0)
        locals()[f'score{i}'] = models.FloatField(default=0.0)
        locals()[f'accuracy{i}'] = models.FloatField(default=0.0)
    result = models.CharField(max_length = 50 , default=" ")

    def __str__(self):
        return f'Player ({self.player.user.username})'

gamified_test/views.py
from django.shortcuts import render
import json
import random
from django.http import JsonResponse
from .models import GameData
from authentication.models import Player
import numpy as np
import pickle
import os
from django.views.decorators.csrf import csrf_exempt

def signin(request):
    return render(request , 'signin.html')
def register(request):
    return render(request , 'register.html')
def q1Screen(request):
    return render(request , 'gamified_test/q1Screen.html')
def q2Screen(request):
    return render(request , 'gamified_test/q2Screen.html')
def q3Screen(request):
    return render(request , 'gamified_test/q3Screen.html')
def q4Screen(request):
    return render(request , 'gamified_test/q4Screen.html')
def q5Screen(request):
    list = [['ne','no','de','na','pu','qu','be','qe','da','pa','ba','pe','da']]
    selected_list = random.choice(list)
    my_list = json.dumps(selected_list)
    return render(request , 'gamified_test/q5Screen.html',{'my_list': my_list})
def q6Screen(request):
    list = [['ne','no','de','na','pu','qu','be','qe','da','pa','ba','pe','da']]
    selected_list = random.choice(list)
    my_list = json.dumps(selected_list)
    return render(request , 'gamified_test/q6Screen.html',{'my_list': my_list})
def q7Screen(request):
    list =  [['pra','par','gar','qar','are','gra','dar','qar','der','ger','gre','bar']]
    selected_list = random.choice(list)
    my_list = json.dumps(selected_list)
    return render(request , 'gamified_test/q7Screen.html',{'my_list': my_list})
def q8Screen(request):
    list = [['pra','par','gar','qar','are','gra','dar','qar','der','ger','gre','bar']]
    selected_list = random.choice(list)
    my_list = json.dumps(selected_list)
    return render(request , 'gamified_test/q8Screen.html',{'my_list': my_list})
def q9Screen(request):
    list = [['grel','glis','glil','gris','gerl']]
    selected_list = random.choice(list)
    my_list = json.dumps(selected_list)
    return render(request , 'gamified_test/q9Screen.html',{'my_list': my_list})
def q10Screen(request):
    list = [
    [
    "create" , "great" , "gate" ,
    "greet" , "crate" , "great" ,
    "greet" , "grade" , "crate"
    ],
    [ "date" , "late" , "deer" ,
      "dear" , "gate" , "ate" ,
      "late" , "door" , "grade"
    ]]
    selected_list = random.choice(list)
    my_list = json.dumps(selected_list)
    return render(request , 'gamified_test/q10Screen.html',{'my_list': my_list})
def q11Screen(request):
    list = [
    ["meet" , "greet" , "great" ,"sweet"
    "seat" , "meet" , "mate" , "neat",
    "sweet" , "grade" , "crate" , "greet",
    "greet" , "neat" , "seat" , "grade",
    ],
    ["blue" , "true" , "you" ,"view",
    "crew" , "you" , "glue" , "shoe",
    "glue" , "clue" , "crew" , "true",
    "true" , "blue" , "knew" , "glue"
    ]
  ]
    selected_list = random.choice(list)
    my_list = json.dumps(selected_list)
    return render(request , 'gamified_test/q11Screen.html',{'my_list': my_list})
def q12Screen(request):
    list = [
    ["shade" , "sheet" , "seed" ,"clean" , "neat",
      "read" , "red" , "cheat" , "chase",  "meat",
      "neat" , "chase" , "chase" , "dress" , "shade",
      "red" , "check" , "read" , "chase" , "net",
      "neat" , "shade" , "red" , "cheat" , "shade"
    ],
    ["coat" , "cough" , "dough" ,"boat" , "gloat",
      "shoot" , "note" , "caught" , "chose",  "loose",
      "mose" , "rough" , "rogue" , "note" , "suit",
      "boot" , "road" , "taught" , "chose" , "nose",
      "note" , "cough" , "mose" , "rough" , "tough"
    ],
  ]
    selected_list = random.choice(list)
    my_list = json.dumps(selected_list)
    return render(request , 'gamified_test/q12Screen.html',{'my_list': my_list})
def q13Screen(request):
    list = [["fly" , "dye" , "tie" ,"fight" , "flight" , "night",
      "rye" , "shy" , "cheat" , "chase",  "meat" ,"red",
      "yield" , "shed" , "sat" , "dress" , "dish","shred",
      "red" , "men" , "read" , "need" , "net", "note",
      "neat" , "meat" , "yield" , "deal" , "read" ,"shed",
      "night" , "dye" , "diet" , "deal" , "tight" , "shy"
    ]]
    selected_list = random.choice(list)
    my_list = json.dumps(selected_list)
    return render(request , 'gamified_test/q13Screen.html',{'my_list': my_list})
def q14Screen(request):
    return render(request , 'gamified_test/q14Screen.html')
def q15Screen(request):
    return render(request , 'gamified_test/q15Screen.html')
def q16Screen(request):
    return render(request , 'gamified_test/q16Screen.html')
def q17Screen(request):
    return render(request , 'gamified_test/q17Screen.html')
def q18Screen(request):
    list = [['matapa','madata','mapaba','damata','pamama','mamata'],
    ['bapama','dapama','madapa','tapama']]
    selected_list = random.choice(list)
    my_list = json.dumps(selected_list)
    return render(request , 'gamified_test/q18Screen.html',{'my_list': my_list})
def q19Screen(request):
    list = [['matapa','madata','mapaba','damata','pamama','mamata'],
    ['bapama','dapama','madapa','tapama']]
    selected_list = random.choice(list)
    my_list = json.dumps(selected_list)
    return render(request , 'gamified_test/q19Screen.html',{'my_list': my_list})
def q20Screen(request):
    list = [['dabaqa','badaqa','dadapa','pabapa',
      'dadapa','dabapa','babada','dabada','pabapa','babapa'] ]
    selected_list = random.choice(list)
    my_list = json.dumps(selected_list)
    return render(request , 'gamified_test/q20Screen.html',{'my_list': my_list})
def q21Screen(request):
    list = [['dabaqa','badaqa','dadapa','pabapa',
      'dadapa','dabapa','babada','dabada','pabapa','babapa'] ]
    selected_list = random.choice(list)
    my_list = json.dumps(selected_list)
    return render(request , 'gamified_test/q21Screen.html',{'my_list': my_list})
def q22Screen(request):
    return render(request , 'gamified_test/q22Screen.html')
def q23Screen(request):
    return render(request , 'gamified_test/q23Screen.html')
def q24Screen(request):
    my_dict = {
        "affect": ['The', 'affect', 'of', 'the', 'wind', 'was', 'to', 'cause', 'the', 'boat’s', 'sail', 'to', 'billow.'],
        "meet": ['The', 'restaurant', 'offers', 'a', 'delicious', 'meet', 'dish', 'for', 'dinner.'],
        "then": ['There', 'are', 'less', 'girls', 'in', 'our', 'class', 'then', 'boys.'],
        "net": ['You', 'must', 'get', 'your', 'neat', 'for', 'fishing.'],
    }
    selected_key = random.choice(list(my_dict.keys()))
    selected_list = my_dict[selected_key]
    my_list = json.dumps(selected_list)
    return render(request, 'gamified_test/q24Screen.html', 
                  {'my_list': my_list},
                  {'selected_key': selected_key} )
def q24Screen(request):
    my_dict = {
        "affect": ['The', 'affect', 'of', 'the', 'wind', 'was', 'to', 'cause', 'the', 'boat’s', 'sail', 'to', 'billow.'],
        "meet": ['The', 'restaurant', 'offers', 'a', 'delicious', 'meet', 'dish', 'for', 'dinner.'],
        "then": ['There', 'are', 'less', 'girls', 'in', 'our', 'class', 'then', 'boys.'],
        "neat": ['You', 'must', 'get', 'your', 'neat', 'for', 'fishing.'],
    }
    selected_key = random.choice(list(my_dict.keys()))
    selected_list = my_dict[selected_key]
    my_list = json.dumps(selected_list)
    return render(request, 'gamified_test/q24Screen.html',
                   {'my_list': my_list,
                   'selected_key': selected_key})
def q25Screen(request):
    my_dict = {
    "of": ['Smoking','is','prohibited','of','the','entire','craft.'],
    "them":  ['This','homework','is','so','easy','.  I','can','do','them' ,'in','five','minutes.'],
    "was": ['I','swim','in','the','sea','whenever','the','weather','was','fine.'],
    "were":['When','we','went','shopping','it','were','very','busy.'],
    }
    selected_key = random.choice(list(my_dict.keys()))
    selected_list = my_dict[selected_key]
    my_list = json.dumps(selected_list)
    return render(request, 'gamified_test/q25Screen.html',
                   {'my_list': my_list,
                   'selected_key': selected_key})
def q26Screen(request):
    return render(request , 'gamified_test/q26Screen.html')
def q27Screen(request):
    return render(request , 'gamified_test/q27Screen.html')
def q28Screen(request):
    return render(request , 'gamified_test/q28Screen.html')
def q29Screen(request):
    return render(request , 'gamified_test/q29Screen.html')
def q30Screen(request):
    return render(request , 'gamified_test/q30Screen.html')
def q31Screen(request):
    list =["socks","hand","make" ,"room","spoon","vegetable", "science","house","elephant","read","shape","note","book","penguin","riddle","glass"]
    my_list = json.dumps(list)
    return render(request , 'gamified_test/q31Screen.html',{'my_list': my_list})
def q32Screen(request):
    list=["smay" ,"crench","qota","wabas","glis","glaba","nana"]
    my_list = json.dumps(list)
    return render(request , 'gamified_test/q32Screen.html',{'my_list': my_list})

@csrf_exempt  # Disable CSRF protection for this view (for simplicity)
def save_performance_data(request, exercise_num):
    if request.method == 'POST':
        # Retrieve performance data from AJAX request
        clicks = request.POST.get('clicks')
        hits = request.POST.get('hits')
        misses = request.POST.get('misses')
        missrate = request.POST.get('missrate')
        score = request.POST.get('score')
        accuracy = request.POST.get('accuracy')

        # retrieves the Player object linked to the currently authenticated user.
        player = request.user.player
        # Get or create GameData object for the player
        game_data, created = GameData.objects.get_or_create(player=player)
        
        # Update performance metrics for the specific exercise
        setattr(game_data, f'clicks{exercise_num}', clicks)
        setattr(game_data, f'hits{exercise_num}', hits)
        setattr(game_data, f'misses{exercise_num}', misses)
        setattr(game_data, f'missrate{exercise_num}', missrate)

gamified_test/templates/gamified_test/q10Screen.html
{%extends 'gridview.html'%}
{%block content%}

{%load static %}
<script src="{%static 'gamified_test/Js/Q5To13-Q18To21.js'%}" type="module" id="myScript"
 data-gridSize="3" data-exerciseNum="10" data-Url="{% url 'gamified_test:q11Screen' %}" data-list="{{ my_list }}"></script>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{%endblock%}

gamified_test/templates/gamified_test/q12Screen.html
{%extends 'gridview.html'%}
{%block content%}

{%load static %}
<script src="{%static 'gamified_test/Js/Q5To13-Q18To21.js'%}" type="module" id="myScript"
 data-gridSize="5" data-exerciseNum="12" data-Url="{% url 'gamified_test:q13Screen' %}" data-list="{{ my_list }}"></script>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{%endblock%}

gamified_test/templates/gamified_test/q13Screen.html
{%extends 'gridview.html'%}
{%block content%}

{%load static %}
<script src="{%static 'gamified_test/Js/Q5To13-Q18To21.js'%}" type="module" id="myScript"
 data-gridSize="6" data-exerciseNum="13" data-Url="{% url 'gamified_test:q14Screen' %}" data-list="{{ my_list }}"></script>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{%endblock%}

gamified_test/templates/gamified_test/q14Screen.html
{%extends 'gridview.html'%}
{%block content%}

{%load static %}
<script src="{%static 'gamified_test/Js/Q14To17_base.js'%}" type="module" id="myScript"
 data-gridSize="5" data-exerciseNum="14" data-Url="{% url 'gamified_test:q15Screen' %}"></script>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{%endblock%}

gamified_test/templates/gamified_test/q18Screen.html
{%extends 'gridview.html'%}
{%block content%}

{%load static %}
<script src="{%static 'gamified_test/Js/Q5To13-Q18To21.js'%}" type="module" id="myScript"
 data-gridSize="3" data-exerciseNum="18" data-Url="{% url 'gamified_test:q19Screen' %}" data-list="{{ my_list }}"></script>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{%endblock%}

gamified_test/templates/gamified_test/q1Screen.html
{%extends 'gridview.html'%}
{%block content%}

{%load static %}
<script src="{%static 'gamified_test/Js/Q1ToQ4_base.js'%}" type="module" id="myScript"
 data-gridSize="3"  data-exerciseNum="1" data-Url="{% url 'gamified_test:q2Screen' %}"></script>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

{%endblock%}

gamified_test/templates/gamified_test/q20Screen.html
{%extends 'gridview.html'%}
{%block content%}

{%load static %}
<script src="{%static 'gamified_test/Js/Q5To13-Q18To21.js'%}" type="module" id="myScript"
 data-gridSize="3" data-exerciseNum="20" data-Url="{% url 'gamified_test:q21Screen' %}" data-list="{{ my_list }}"></script>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{%endblock%}

gamified_test/templates/gamified_test/q27Screen.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'gamified_test/css/Q27ToQ28Screen.css'%}">
</head>
<body>
    <div class="container">
        <div id="word-container" class="word-container"></div>
        <div id="letters-container" class="letters-container"></div>
         {%include 'progressbar.html'%}
    </div>
    <script id="myScript" src="{%static 'gamified_test/Js/Q27Screen.js'%}" type="module"
     data-url="{% url 'gamified_test:q28Screen' %}" data-exerciseNum="27"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</body>
</html>

gamified_test/templates/gamified_test/q31Screen.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'gamified_test/css/Q30ToQ32Screen.css'%}">
</head>
<body>
    <div class="container" id="screen">
        <div class="message" id="wordMessage">Type here:</div>
        <input type="text" id="userInput">
        {%include 'progressbar.html'%}
    </div>
    <script id="myScript" src="{%static 'gamified_test/Js/Q31ToQ32Screen.js'%}" type="module" 
    data-url = "{% url 'gamified_test:q32Screen' %}" data-exerciseNum="31" data-list="{{ my_list }}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</body>
</html>

gamified_test/templates/gamified_test/q32Screen.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{%static 'gamified_test/css/Q30ToQ32Screen.css'%}">
</head>
<body>
    <div class="container" id="screen">
        <div class="message" id="wordMessage">Type here:</div>
        <input type="text" id="userInput">
        {%include 'progressbar.html'%}
    </div>
    <script id="myScript" src="{%static 'gamified_test/Js/Q31ToQ32Screen.js'%}" type="module"
    data-list="{{ my_list }}" data-url = "{% url 'gamified_test:result' %}" data-exerciseNum="32"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</body>
</html>

gamified_test/templates/gamified_test/q9Screen.html
{%extends 'gridview.html'%}
{%block content%}

{%load static %}
<script src="{%static 'gamified_test/Js/Q5To13-Q18To21.js'%}" type="module" id="myScript"
 data-gridSize="3"  data-exerciseNum="9" data-Url="{% url 'gamified_test:q10Screen' %}" data-list="{{ my_list }}"></script>
 <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{%endblock%}

gamified_test/templates/gamified_test/result.html
{% extends "authentication/base.html" %}
{% load static %} 

{% block content %}
    <link rel="stylesheet" href="{% static 'gamified_test/css/result.css' %}">
    <div class="container">
        <div class="card w-55">
            <div class="card-body">
                <h1 class="card-title"><strong>Dyadapt Gamified Screening Test</strong></h1>
                <p class="date">Date: {{ date }}</p>
                <div class="result">Result: {{ result }}</div>
                {% if result == 'High-Risk' %}
                    <div class="eyetracking-container">
                        <p>Proceed to eye-tracking for further assessment.</p>
                        <a href="{% url 'eyeTracking:eyeTracking' %}" id="goToEyeTrackingBtn" class="btn btn-primary" role="button">Proceed to Eye Tracking</a>
                    </div>
                {% elif result == 'Low-Risk' %}
                    <div class="adaptation-container">
                        <p>Do you want reading to be easier?</p>
                        <a href="{% url 'adaptation:base' %}" id="goToAdaptationBtn" class="btn btn-primary" role="button">Go to adaptation</a>
                    </div>
                {% else %}
                    <p>Invalid result value</p>
                {% endif %}
                
            </div>
        </div>
    </div> 
{% endblock %}

gamified_test/templates/gamified_test/result_highrisk.html
{% extends "authentication/base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'gamified_test/css/result.css' %}">
    <div class="container">
        <div class="card w-55">
            <div class="card-body">
                <h1 class="card-title"><strong>Dyadapt Gamified Screening Test</strong></h1>
                <p class="date">Date:    {{ date }}</p> 
                <div class="result">{{ result }}</div>
                <div class="adaptation-container">
                    <p>Do you want reading to be easier?</p>
                    <button id="adaptationBtn">Go to adaptation</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

gamified_test/templates/gamified_test/result_lowrisk.html
{% extends "authentication/base.html" %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'gamified_test/css/result.css' %}">
    <div class="container">
        <div class="card w-55">
            <div class="card-body">
                <h1 class="card-title"><strong>Dyadapt Gamified Screening Test</strong></h1>
                <p class="date">Date:    {{ date }}</p> 
                <div class="result">{{ result }}</div>
                {% we need to redirect this page to the eyetracking %}
                <div class="eyetracking-container">
                    <button id="eyetrackingBtn">Proceed To Eyetracking</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}